#!/usr/bin/env node
/**
 * Deploys USDT/BTC/ETH test tokens via script/DeployTestTokens.s.sol (which
 * deploys the single MintableTestToken contract three times, once per
 * symbol), then writes ../nextjs/contracts/deployedContracts.ts with one
 * named entry per deployment, all sharing MintableTestToken's ABI.
 *
 * One generic contract, deployed N times with different constructor args —
 * mirrors fce-orderbook's tools/cmd/test-setup pattern (a single TestToken.sol
 * deployed once per symbol via a Go loop). This is the same idea via a
 * Foundry script since this repo's tooling is Node/Foundry, not Go.
 *
 * `forge create` was tried first (simpler, one call per token) but throws
 * "Device not configured (os error 6)" in this sandbox — some TTY probe it
 * does that `forge script` doesn't. Hence `forge script` + parsing the
 * broadcast log instead.
 *
 * generateTsAbis.js can't be reused for this: it dedupes deployments by
 * `${chainId}-${contractName}`, so multiple instances of the same Solidity
 * contract class collapse to just the last one. Hence this separate script,
 * which keys entries by the caller-supplied token key instead — matched to
 * the broadcast's CREATE transactions *by order*, since every deployment
 * shares the literal contract name "MintableTestToken" and can't be told
 * apart by name. TOKENS_TO_DEPLOY's order must match
 * DeployTestTokens.s.sol's deployment order exactly.
 *
 * IMPORTANT: generateTsAbis.js (run by `yarn deploy`, e.g. for any other
 * single-instance contract) fully REGENERATES deployedContracts.ts from its
 * own broadcast scan and has no idea about the entries this script writes —
 * running it clobbers FlrTestToken/UsdtTestToken/BtcTestToken/EthTestToken
 * (and collapses MintableTestToken's 3 deployments into one, under the
 * literal class name). Run this script with --restore-only afterward to put
 * them back, at no gas cost — it doesn't deploy anything in that mode, just
 * re-merges the known addresses (below) into whatever's currently on disk.
 *
 * Usage:
 *   node scripts-js/deployTestTokens.js --network coston2 --keystore coston2-deployer [--password-file <path>]
 *   node scripts-js/deployTestTokens.js --restore-only   # no deploy, no gas — just re-merge known addresses
 */
import { spawnSync } from "child_process";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));
const foundryRoot = join(__dirname, "..");
const deployedContractsPath = join(foundryRoot, "../nextjs/contracts/deployedContracts.ts");

const CHAIN_IDS = { coston2: 114 };

// Order must match script/DeployTestTokens.s.sol's deployment order.
const TOKENS_TO_DEPLOY = [
  { key: "UsdtTestToken", name: "Tether USD (Test)", symbol: "USDT", decimals: 6 },
  { key: "BtcTestToken", name: "Bitcoin (Test)", symbol: "BTC", decimals: 8 },
  { key: "EthTestToken", name: "Ether (Test)", symbol: "ETH", decimals: 18 },
];

// Known-good addresses already live on Coston2 — used by --restore-only, and as a
// fallback in normal mode if one's missing from the current deployedContracts.ts
// (e.g. it was clobbered by another deploy before this script got a chance to run).
// FLR was deployed separately, as its own FlrTestToken contract, before this script
// existed — it's not one of TOKENS_TO_DEPLOY, but still needs restoring the same way.
const KNOWN_TOKEN_ADDRESSES = {
  FlrTestToken: "0x591B11abe90E8D832F04aa9E84fcEe6D3c394699",
  UsdtTestToken: "0xC5b806B354DBe263b2D567Ea162D3802F25E764e",
  BtcTestToken: "0x8aefDDdC40CF83fC82A7dEB4bd3F1894e76c43cd",
  EthTestToken: "0x08cE174E493f9E62c82BbCB707991658c8f2AA39",
};

function getArg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 ? process.argv[i + 1] : fallback;
}
function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function readExistingEntries(chainId) {
  if (!existsSync(deployedContractsPath)) return {};
  const source = readFileSync(deployedContractsPath, "utf-8");
  // deployedContracts.ts is generated code, not hand-authored — safe to eval
  // as a module body here rather than hand-parsing its object literal.
  const objectLiteral = source
    .replace(/^[\s\S]*const deployedContracts = /, "")
    .replace(/\s*as const;[\s\S]*$/, "");
  // eslint-disable-next-line no-eval
  const parsed = (0, eval)(`(${objectLiteral})`);
  const chainEntries = parsed[chainId] ?? {};
  // Dead orphans from earlier mis-named / collapsed-by-generateTsAbis deploys.
  delete chainEntries.TestToken;
  delete chainEntries.MintableTestToken;
  return chainEntries;
}

async function writeEntries(chainId, entries) {
  const fileContent = `
    /**
     * This file is autogenerated by scripts-js/deployTestTokens.js.
     * You should not edit it manually or your changes might be overwritten.
     */
    import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

    const deployedContracts = {${chainId}: ${JSON.stringify(entries)}} as const;

    export default deployedContracts satisfies GenericContractsDeclaration;
  `;
  writeFileSync(deployedContractsPath, await format(fileContent, { parser: "typescript", printWidth: 120 }));
  console.log(`Wrote ${deployedContractsPath}`);
}

async function main() {
  const network = getArg("network", "coston2");
  const chainId = CHAIN_IDS[network];
  if (!chainId) {
    console.error(`Unknown network "${network}" — add it to CHAIN_IDS in this script`);
    process.exit(1);
  }

  const artifactPath = join(foundryRoot, "out/MintableTestToken.sol/MintableTestToken.json");
  if (!existsSync(artifactPath)) {
    console.error(`Missing build artifact at ${artifactPath} — run \`forge build\` first`);
    process.exit(1);
  }
  const abi = JSON.parse(readFileSync(artifactPath, "utf-8")).abi;

  const entries = readExistingEntries(chainId);

  if (hasFlag("restore-only")) {
    for (const [key, address] of Object.entries(KNOWN_TOKEN_ADDRESSES)) {
      entries[key] = { address, abi };
      console.log(`  ${key} -> ${address}`);
    }
    await writeEntries(chainId, entries);
    return;
  }

  const keystore = getArg("keystore");
  const passwordFile = getArg("password-file");
  if (!keystore) {
    console.error("Usage: node deployTestTokens.js --network <net> --keystore <name> [--password-file <path>]");
    console.error("   or: node deployTestTokens.js --restore-only");
    process.exit(1);
  }

  console.log(`Deploying ${TOKENS_TO_DEPLOY.map(t => t.symbol).join(", ")} via DeployTestTokens.s.sol...`);
  const forgeArgs = [
    "script",
    "script/DeployTestTokens.s.sol",
    "--rpc-url",
    network,
    "--account",
    keystore,
    "--broadcast",
    "--ffi",
  ];
  if (passwordFile) forgeArgs.push("--password-file", passwordFile);

  const result = spawnSync("forge", forgeArgs, { cwd: foundryRoot, encoding: "utf-8", stdio: "inherit" });
  if (result.status !== 0) {
    process.exit(1);
  }

  const broadcastPath = join(foundryRoot, `broadcast/DeployTestTokens.s.sol/${chainId}/run-latest.json`);
  const broadcast = JSON.parse(readFileSync(broadcastPath, "utf-8"));
  const createTxs = broadcast.transactions.filter(tx => tx.transactionType === "CREATE");
  if (createTxs.length !== TOKENS_TO_DEPLOY.length) {
    console.error(
      `Expected ${TOKENS_TO_DEPLOY.length} CREATE txs in ${broadcastPath}, found ${createTxs.length}. ` +
        `Did DeployTestTokens.s.sol change without updating TOKENS_TO_DEPLOY here?`,
    );
    process.exit(1);
  }
  const blockByAddress = Object.fromEntries(
    broadcast.receipts.map(r => [r.contractAddress, parseInt(r.blockNumber, 16)]),
  );

  // FLR isn't redeployed here, but restore it if it's missing from what's on disk.
  entries.FlrTestToken ??= { address: KNOWN_TOKEN_ADDRESSES.FlrTestToken, abi };

  TOKENS_TO_DEPLOY.forEach((token, i) => {
    const address = createTxs[i].contractAddress;
    entries[token.key] = { address, abi, deployedOnBlock: blockByAddress[address] };
    console.log(`  ${token.key} -> ${address}`);
  });

  await writeEntries(chainId, entries);
}

main();
