#!/usr/bin/env node
/**
 * Deploys a SeedTokenFactory, clones one SeedToken per entry in
 * script/mocks/tokens.json, and deploys a Faucet wired up to all of them, via
 * script/mocks/DeployTestTokens.s.sol. Writes
 * ../nextjs/contracts/deployedContracts.ts with SeedTokenFactory and Faucet
 * entries plus one named entry per token clone (all sharing SeedToken's ABI).
 *
 * `forge create` was tried first (simpler, one call per token) but throws
 * "Device not configured (os error 6)" in this sandbox — some TTY probe it
 * does that `forge script` doesn't. Hence `forge script` + parsing the
 * broadcast log instead.
 *
 * generateTsAbis.js can't be reused for this: it dedupes deployments by
 * `${chainId}-${contractName}`, so multiple SeedToken clones (all sharing
 * the literal contract name "SeedToken") would collapse to just the last
 * one. Hence this separate script, which keys entries by the caller-supplied
 * token key instead.
 *
 * SeedTokenFactory.deployToken() is a CALL, not a CREATE — the clone address
 * isn't in the transaction's top-level fields the way a CREATE's is, so this
 * reads it out of each call's TokenDeployed(address,string,string) event log
 * instead, then cross-checks the log's symbol against tokens.json's to catch
 * any order drift between the two.
 *
 * IMPORTANT: generateTsAbis.js (run by `yarn deploy`, e.g. for any other
 * single-instance contract) fully REGENERATES deployedContracts.ts from its
 * own broadcast scan and has no idea about the entries this script writes —
 * running it clobbers every key in KNOWN_TOKEN_ADDRESSES below (and collapses
 * every SeedToken clone into one, under the literal class name). Run this
 * script with --restore-only afterward to put them back, at no gas cost — it
 * doesn't deploy anything in that mode, just re-merges the known addresses
 * (below) into whatever's currently on disk.
 *
 * Usage:
 *   node scripts-js/deployTestTokens.js --network coston2 --keystore coston2-deployer [--password-file <path>]
 *   node scripts-js/deployTestTokens.js --restore-only   # no deploy, no gas — just re-merge known addresses
 */
import { spawnSync } from "child_process";
import { existsSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";
import { utils } from "ethers";

const __dirname = dirname(fileURLToPath(import.meta.url));
const foundryRoot = join(__dirname, "..");
const deployedContractsPath = join(
  foundryRoot,
  "../nextjs/contracts/deployedContracts.ts"
);

const CHAIN_IDS = { coston2: 114 };

// Same file DeployTestTokens.s.sol reads — order here is authoritative for
// both, since deployToken() calls come back in this array's order.
const TOKENS_TO_DEPLOY = JSON.parse(
  readFileSync(join(foundryRoot, "script/mocks/tokens.json"), "utf-8")
);

const TOKEN_DEPLOYED_TOPIC = utils.id("TokenDeployed(address,string,string)");

// Known-good addresses already live on Coston2 — used by --restore-only, and as a
// fallback in normal mode if one's missing from the current deployedContracts.ts
// (e.g. it was clobbered by another deploy before this script got a chance to run).
// FLR was deployed separately, as its own FlrTestToken contract, before this script
// existed — it's not one of TOKENS_TO_DEPLOY, but still needs restoring the same way.
const KNOWN_TOKEN_ADDRESSES = {
  FlrTestToken: "0x591B11abe90E8D832F04aa9E84fcEe6D3c394699",
};

function getArg(name, fallback) {
  const i = process.argv.indexOf(`--${name}`);
  return i !== -1 ? process.argv[i + 1] : fallback;
}
function hasFlag(name) {
  return process.argv.includes(`--${name}`);
}

function readExistingEntries(chainId) {
  if (!existsSync(deployedContractsPath)) return {};
  const source = readFileSync(deployedContractsPath, "utf-8");
  // deployedContracts.ts is generated code, not hand-authored — safe to eval
  // as a module body here rather than hand-parsing its object literal.
  const objectLiteral = source
    .replace(/^[\s\S]*const deployedContracts = /, "")
    .replace(/\s*as const;[\s\S]*$/, "");
  // eslint-disable-next-line no-eval
  const parsed = (0, eval)(`(${objectLiteral})`);
  const chainEntries = parsed[chainId] ?? {};
  // Dead orphans from earlier mis-named / collapsed-by-generateTsAbis deploys.
  delete chainEntries.TestToken;
  delete chainEntries.MintableTestToken;
  delete chainEntries.SeedToken;
  return chainEntries;
}

async function writeEntries(chainId, entries) {
  const fileContent = `
    /**
     * This file is autogenerated by scripts-js/deployTestTokens.js.
     * You should not edit it manually or your changes might be overwritten.
     */
    import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

    const deployedContracts = {${chainId}: ${JSON.stringify(entries)}} as const;

    export default deployedContracts satisfies GenericContractsDeclaration;
  `;
  writeFileSync(
    deployedContractsPath,
    await format(fileContent, { parser: "typescript", printWidth: 120 })
  );
  console.log(`Wrote ${deployedContractsPath}`);
}

function loadAbi(contractName) {
  const artifactPath = join(
    foundryRoot,
    `out/${contractName}.sol/${contractName}.json`
  );
  if (!existsSync(artifactPath)) {
    console.error(
      `Missing build artifact at ${artifactPath} — run \`forge build\` first`
    );
    process.exit(1);
  }
  return JSON.parse(readFileSync(artifactPath, "utf-8")).abi;
}

async function main() {
  const network = getArg("network", "coston2");
  const chainId = CHAIN_IDS[network];
  if (!chainId) {
    console.error(
      `Unknown network "${network}" — add it to CHAIN_IDS in this script`
    );
    process.exit(1);
  }

  const factoryAbi = loadAbi("SeedTokenFactory");
  const tokenAbi = loadAbi("SeedToken");
  const faucetAbi = loadAbi("Faucet");

  const entries = readExistingEntries(chainId);

  if (hasFlag("restore-only")) {
    for (const [key, address] of Object.entries(KNOWN_TOKEN_ADDRESSES)) {
      entries[key] = { address, abi: tokenAbi };
      console.log(`  ${key} -> ${address}`);
    }
    await writeEntries(chainId, entries);
    return;
  }

  const keystore = getArg("keystore");
  const passwordFile = getArg("password-file");
  if (!keystore) {
    console.error(
      "Usage: node deployTestTokens.js --network <net> --keystore <name> [--password-file <path>]"
    );
    console.error("   or: node deployTestTokens.js --restore-only");
    process.exit(1);
  }

  console.log(
    `Deploying SeedTokenFactory + ${TOKENS_TO_DEPLOY.map((t) => t.symbol).join(
      ", "
    )}...`
  );
  const forgeArgs = [
    "script",
    "script/mocks/DeployTestTokens.s.sol",
    "--rpc-url",
    network,
    "--account",
    keystore,
    "--broadcast",
    "--ffi",
  ];
  if (passwordFile) forgeArgs.push("--password-file", passwordFile);

  const result = spawnSync("forge", forgeArgs, {
    cwd: foundryRoot,
    encoding: "utf-8",
    stdio: "inherit",
  });
  if (result.status !== 0) {
    process.exit(1);
  }

  const broadcastPath = join(
    foundryRoot,
    `broadcast/DeployTestTokens.s.sol/${chainId}/run-latest.json`
  );
  const broadcast = JSON.parse(readFileSync(broadcastPath, "utf-8"));

  const factoryTx = broadcast.transactions.find(
    (tx) =>
      tx.transactionType === "CREATE" && tx.contractName === "SeedTokenFactory"
  );
  if (!factoryTx) {
    console.error(`No SeedTokenFactory CREATE tx found in ${broadcastPath}`);
    process.exit(1);
  }
  const factoryAddress = factoryTx.contractAddress;

  const deployCallTxs = broadcast.transactions.filter(
    (tx) =>
      tx.transactionType === "CALL" &&
      tx.transaction.to?.toLowerCase() === factoryAddress.toLowerCase()
  );
  if (deployCallTxs.length !== TOKENS_TO_DEPLOY.length) {
    console.error(
      `Expected ${TOKENS_TO_DEPLOY.length} deployToken() calls in ${broadcastPath}, found ${deployCallTxs.length}. ` +
        `Did DeployTestTokens.s.sol change without updating tokens.json (or vice versa)?`
    );
    process.exit(1);
  }

  const faucetTx = broadcast.transactions.find(
    (tx) => tx.transactionType === "CREATE" && tx.contractName === "Faucet"
  );
  if (!faucetTx) {
    console.error(`No Faucet CREATE tx found in ${broadcastPath}`);
    process.exit(1);
  }

  const receiptByHash = Object.fromEntries(
    broadcast.receipts.map((r) => [r.transactionHash, r])
  );
  const blockByAddress = Object.fromEntries(
    broadcast.receipts.map((r) => [
      r.contractAddress,
      parseInt(r.blockNumber, 16),
    ])
  );

  // FLR isn't redeployed here, but restore it if it's missing from what's on disk.
  entries.FlrTestToken ??= {
    address: KNOWN_TOKEN_ADDRESSES.FlrTestToken,
    abi: tokenAbi,
  };

  entries.SeedTokenFactory = {
    address: factoryAddress,
    abi: factoryAbi,
    deployedOnBlock: blockByAddress[factoryAddress],
  };
  console.log(`  SeedTokenFactory -> ${factoryAddress}`);

  TOKENS_TO_DEPLOY.forEach((token, i) => {
    const receipt = receiptByHash[deployCallTxs[i].hash];
    const log = receipt.logs.find((l) => l.topics[0] === TOKEN_DEPLOYED_TOPIC);
    if (!log) {
      console.error(
        `No TokenDeployed log found for ${token.symbol} in tx ${deployCallTxs[i].hash}`
      );
      process.exit(1);
    }
    const address = utils.getAddress(`0x${log.topics[1].slice(-40)}`);
    entries[token.key] = {
      address,
      abi: tokenAbi,
      deployedOnBlock: parseInt(receipt.blockNumber, 16),
    };
    console.log(`  ${token.key} -> ${address}`);
  });

  entries.Faucet = {
    address: faucetTx.contractAddress,
    abi: faucetAbi,
    deployedOnBlock: blockByAddress[faucetTx.contractAddress],
  };
  console.log(`  Faucet -> ${faucetTx.contractAddress}`);

  await writeEntries(chainId, entries);
}

main();
