#!/usr/bin/env node
/**
 * Reads data/token.json (the deployed Faucet's test-token list) and emits a
 * typed ../nextjs/utils/testTokens.ts the faucet UI imports directly, instead
 * of hand-copying addresses after every SeedTokenFactory deploy. Mirrors
 * deployTestTokens.js's shape/conventions.
 *
 * data/token.json is currently 114-only (Coston2, this app's one target
 * network) and isn't chain-keyed the way deployedContracts.ts is - if a
 * second network's faucet ever gets deployed, this script (and
 * useDepositableTokens.ts, which consumes its output) will need to grow a
 * chain dimension too.
 *
 * Run with: node scripts-js/syncTestTokens.js
 */
import { readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";
import { format } from "prettier";

const __dirname = dirname(fileURLToPath(import.meta.url));
const foundryRoot = join(__dirname, "..");
const dataPath = join(foundryRoot, "data/token.json");
const outFile = join(foundryRoot, "../nextjs/utils/testTokens.ts");

const raw = JSON.parse(readFileSync(dataPath, "utf-8"));

// Skip anything without a real address rather than emitting a token the
// faucet could never actually send.
let skipped = 0;
const tokens = raw
  .filter(e => {
    const ok = typeof e.token === "string" && e.token.length > 0;
    if (!ok) skipped++;
    return ok;
  })
  .map(e => ({
    address: e.token,
    symbol: String(e.symbol ?? ""),
    name: String(e.name ?? ""),
    decimals: Number(e.decimals ?? 18),
    logoURI: String(e.logoURI ?? ""),
  }));
if (skipped > 0) {
  console.log(`  skipped ${skipped} entr(ies) missing a token address`);
}

const banner = `// AUTO-GENERATED by packages/foundry/scripts-js/syncTestTokens.js - do not edit by hand.
// Re-run \`node scripts-js/syncTestTokens.js\` from packages/foundry after data/token.json changes.

`;
const iface = `export interface TestToken {
  address: \`0x\${string}\`;
  symbol: string;
  name: string;
  decimals: number;
  logoURI: string;
}

`;
const body = `export const TEST_TOKENS: TestToken[] = ${JSON.stringify(tokens, null, 2)};\n`;

const content = await format(banner + iface + body, { parser: "typescript", printWidth: 120 });
writeFileSync(outFile, content);
console.log(`wrote ${outFile} (${tokens.length} token(s))`);
